import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";
import {BASE_API} from "@/util/config";
import {ApiResponse} from "@/util/ApiResponse";
import { Todo } from "@/app/components/TodoWithReducer";


export const todoApiSlice = createApi({
    baseQuery: fetchBaseQuery({ baseUrl: BASE_API }),
    reducerPath: "todoApi",
    // Tag types are used for caching and invalidation.
    tagTypes: ["Todos"],
    endpoints: (build) => ({

        getTodos: build.query<ApiResponse<Todo[]>, undefined>({
            query: () => `/api/todos`,
            //transformResponse: (response: ApiResponse<Todo[]>, meta, arg) =>response.data,
            providesTags: (result, error, id) => [{ type: "Todos", id }],
        }),
        deleteTodo: build.mutation<ApiResponse<Todo>, Todo>({
            query: (todo:Todo) =>({
                url:  `/api/todos/${todo._id}`,
                method: 'DELETE',
            }),
            invalidatesTags: ['Todos'],
        }),
    }),
});

// Hooks are auto-generated by RTK-Query
// Same as `quotesApiSlice.endpoints.getQuotes.useQuery`
export const { useGetTodosQuery,
    useDeleteTodoMutation,
        } = todoApiSlice;