import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";
import {BASE_API} from "@/util/config";
import {ApiResponse} from "@/util/ApiResponse";


export interface Todo
{
    _id?: number|string;
    title: string;
    completed: boolean;
}
export const todoApiSlice = createApi({
    baseQuery: fetchBaseQuery({ baseUrl: BASE_API }),
    //refetchOnFocus: true,
    reducerPath: "api",
    // Tag types are used for caching and invalidation.
    tagTypes: ["Todos","Movies","Reviews"],
    endpoints: (build) => ({

        getTodos: build.query<Todo[], undefined>({
            query: () => `/api/todos`,
            transformResponse: (response: ApiResponse<Todo[]>, meta, arg):Array<Todo> =>response.data,
            providesTags: (result, error, id) => [{ type: "Todos", id }],
        }),
        //pessmistic
        saveTodo: build.mutation<ApiResponse<Todo>, Todo>({
            query: (todo:Todo) =>({
                url:  `/api/todos`,
                method: 'POST',
                body:todo,
            }),
            //invalidatesTags: ['Todos'],
            //optimistic update
            async onQueryStarted(todo, { dispatch, queryFulfilled }) {
                console.log('saveTodo ',todo);
                try {
                    const { data: savedTodo } = await queryFulfilled
                    const saveResult = dispatch(
                        todoApiSlice.util.updateQueryData('getTodos', undefined, (draft) => {
                            draft.push(savedTodo.data);
                            return draft;
                        }),
                    )
                } catch(e) {
                    console.log('error ',e);
                }
            },
        }),
        //optimistic update
        deleteTodo: build.mutation<ApiResponse<Todo>, Todo>({
            query: (todo:Todo) =>({
                url:  `/api/todos/${todo._id}`,
                method: 'DELETE',
            }),
            //invalidatesTags: ['Todos'],

            async onQueryStarted(todo, { dispatch, queryFulfilled }) {
                const deleteResult = dispatch(
                    todoApiSlice.util.updateQueryData('getTodos', undefined, (draft) => {
                        draft = draft.filter(td=>td._id!==todo._id);
                        return draft;
                    }),
                )
                try {
                    await queryFulfilled
                } catch {
                    deleteResult.undo()
                }
            },
        }),
        //optimistic update
        updateTodo: build.mutation<ApiResponse<Todo>, Todo>({
            query: (todo:Todo) =>({
                url:  `/api/todos/${todo._id}`,
                method: 'PUT',
                body:todo,
            }),
            //invalidatesTags: ['Todos'],

            async onQueryStarted(todo, { dispatch, queryFulfilled }) {
                const updateResult = dispatch(
                    todoApiSlice.util.updateQueryData('getTodos', undefined, (draft) => {
                        draft = draft.map(td=>td._id==todo._id?todo:td);
                        return draft;
                    }),
                )
                try {
                    await queryFulfilled
                } catch {
                    updateResult.undo()
                }
            },
        }),
    }),
});

// Hooks are auto-generated by RTK-Query
// Same as `quotesApiSlice.endpoints.getQuotes.useQuery`
export const {
    useGetTodosQuery,
    useSaveTodoMutation,
    useUpdateTodoMutation,
    useDeleteTodoMutation,
} = todoApiSlice;